add logo sample to pspsdk
pspdev/pspsdk pull request #133
Opened 2023-05-27 19:44 UTC by pyroesp

"logo" is a fun little sample plugin that draws and bounces a DVD logo around on screen.

Use this if you ever want to draw on screen from a plugin.

2023-05-27 19:48 UTC, pyroesp commented
I couldn't get a screenshot of it with prxshot so here's a little clip on youtube I just uploaded:
https://www.youtube.com/watch?v=Ez4EeNwWtfY

2023-05-27 21:21 UTC, MotoLegacy requested changes
Really cool PR! Definitely something good to have in our samples.

Requested some changes though, see comments! Additionally — could you name it something other than `logo`? Like `image_display` or something, so it feels more agnostic to usage.

2023-05-27 21:21 UTC, MotoLegacy commented on src/samples/prx/logo/Makefile.sample
> +PSP_FW_VERSION = 660
Firmware-agnostic samples are preferred, could you do away with this?

2023-05-27 21:21 UTC, MotoLegacy commented on src/samples/prx/logo/main.c
> +#include <pspkernel.h>
Missing the license header here, check out existing samples to use as a point of reference.

2023-05-27 21:21 UTC, MotoLegacy commented on src/samples/prx/logo/main.c
> +u8 logo[] = {
We definitely don't have ownership of the DVD Video logo. Could you make something yourself to take its place? (Make sure to squash the commits, too, to avoid it being present in our revisions 🙂)

2023-05-28 03:11 UTC, pyroesp commented
@MotoLegacy please have another look, should be ok now.
Image has been changed to a smiley, and everything else asked has been done too.

2023-05-28 03:14 UTC, MotoLegacy approved these changes

2023-05-28 15:32 UTC, pyroesp commented
updated PR title to more accurately represent what the sample is

2023-05-29 11:12 UTC, sharkwouter approved these changes

2023-05-29 11:12 UTC, merged