Refactor Controller Kernel Library documentation
pspdev/pspsdk pull request #181
Opened 2024-03-06 19:18 UTC by Sokus

I've tried to clean up Controller docs a little bit as well as provide additional info about which functions could block program execution.

2024-03-06 19:23 UTC, Sokus commented on src/ctrl/pspctrl.h
> - * @par Example:
Having good quality description of APIs/data structures should be enough to make use of latch data - we also have a very similar example in the samples.

2024-03-06 19:27 UTC, Sokus commented on src/samples/controller/basic/main.c
> -#define printf	pspDebugScreenPrintf
I don't know what is the general stance on this, but I don't think an alias for `printf` is a good idea.

2024-03-06 19:28 UTC, Sokus commented on src/ctrl/pspctrl.h
> - *
Having good quality description of APIs/data structures should be enough to make use of latch data - we also have a very similar example in the samples.

2024-03-06 19:29 UTC, Sokus commented on src/samples/controller/basic/main.c
> -
I am not entirely sure what was that for - seems like a copy-paste error to me.

2024-03-06 19:34 UTC, Sokus commented on src/ctrl/pspctrl.h
> + * @endparblock
`@parblock` and `@endparblock` tags are here just to separate two different notes (otherwise they would merge together). This is something I've read on the internet so I am not sure if I can do something like this or there is another way.

2024-03-07 04:19 UTC, sajattack commented on src/samples/controller/basic/main.c
> -#define printf	pspDebugScreenPrintf
it's just an example?

2024-03-07 08:17 UTC, sharkwouter requested changes
Thanks for this pull request! It's really cool to see someone go into the way the documentation is laid out and improve it!

Most of my comments are about code examples in the docs that are being removed with this PR. I understand that some of it is also available in the example in the samples directory, but it's nicer to have the information multiple times than have it very spread out. It's nice to have the extra context. Otherwise this looks like a nice improvement, thanks a lot for working on this!

2024-03-07 08:19 UTC, sharkwouter commented on src/samples/controller/basic/main.c
> -#define printf	pspDebugScreenPrintf
I'd say this example is slightly better without it. The alias is a bit of a weird practice.

2024-03-07 08:19 UTC, sharkwouter commented on src/samples/controller/basic/main.c
> -
Seems like it. Thanks for removing it.

2024-03-07 08:24 UTC, Sokus commented
@sharkwouter Thanks for the review! I will go back and address the comments - by the way, does it matter if there are multiple commits in a PR? Should they be squashed?

2024-03-07 08:36 UTC, Sokus commented on src/samples/controller/basic/main.c
> +    	sceCtrlReadBufferPositive(&pad, 1);
Could you explain why? Wasn't it misaligned before? (one indent too much)

2024-03-07 16:03 UTC, Sokus commented on src/ctrl/pspctrl.h
> - *
I've restored the example, resolving the conversation.

2024-03-07 16:05 UTC, Sokus commented on src/ctrl/pspctrl.h
> - * and comparing the currently collected button sampling data with the previously collected one.
I've restored deleted info.

2024-03-07 16:05 UTC, Sokus commented on src/ctrl/pspctrl.h
> - * @endcode
Restored the example.

2024-03-07 16:08 UTC, Sokus commented on src/samples/controller/basic/main.c
> +    	sceCtrlReadBufferPositive(&pad, 1);
I investigated it and I noticed it was a mix of 4 spaces and a tab, maybe it rendered differently somehow? I've copied the whitespace form the line above so it should be okay now 🤷‍♂️

2024-03-07 19:56 UTC, merged