cmake/make: use -isystem for system libc headers
pspdev/pspsdk pull request #191
Opened 2024-03-29 21:05 UTC by rofl0r

using -isystem for the libc standard include directory is the only way to make it the first candidate for #include <foo> path search (and not to search `#include "bar"`), and to suppress warnings when building 3rd party code including them.

in order to workaround that, SDL's CI used  a custom patch https://github.com/libsdl-org/SDL/blob/4659a84bd1aebeeeac94793afb046a4059e8366d/.github/workflows/psp.yml#L21 and not having it in my config caused the system headers to be wrongly included during SDL3 build, causing a hard-to-debug error: https://github.com/libsdl-org/SDL/issues/9378

2024-03-31 01:23 UTC, diamant3 requested changes

2024-03-31 08:57 UTC, rofl0r commented on src/base/pspdev.cmake
> +SET(CMAKE_C_FLAGS_INIT "-isystem ${PSPDEV}/psp/include -I${PSPDEV}/psp/sdk/include -DPSP")
i don't have any C++ code to test, but the compiler options are the same so i dont see why it wouldn't behave the same. the libstdc++ code is anyway inside a subdirectory of the compiler install, so it is already treated as a system header directory. the only thin that was missing is that the main libc header directory is recognized as being "system".

2024-03-31 09:20 UTC, rofl0r commented on src/base/pspdev.cmake
> +SET(CMAKE_C_FLAGS_INIT "-isystem ${PSPDEV}/psp/include -I${PSPDEV}/psp/sdk/include -DPSP")
> but it will result an error with c++ libraries in cmake

wait, is this a question or a statement ? i assumed the former. did you actually get an error using C++ with this change ? if so, what was it ?

2024-03-31 09:42 UTC, diamant3 commented on src/base/pspdev.cmake
> +SET(CMAKE_C_FLAGS_INIT "-isystem ${PSPDEV}/psp/include -I${PSPDEV}/psp/sdk/include -DPSP")
sorry, that's a statement, i did test a while ago, here's the error:

```
[100%] Linking CXX executable oceanpop
/usr/local/pspdev/lib/gcc/psp/13.2.0/../../../../psp/bin/ld: /usr/local/pspdev/psp/lib/libstdc++.a(fs_ops.o): in function `_ZNSt10filesystem8do_spaceEPKcRyS2_S2_RSt10error_code':
(.text._ZNSt10filesystem8do_spaceEPKcRyS2_S2_RSt10error_code+0x2c): undefined reference to `statvfs'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/oceanpop.dir/build.make:433: oceanpop] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/oceanpop.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

2024-03-31 10:12 UTC, rofl0r commented on src/base/pspdev.cmake
> +SET(CMAKE_C_FLAGS_INIT "-isystem ${PSPDEV}/psp/include -I${PSPDEV}/psp/sdk/include -DPSP")
that's odd. this is a linker error, and it means that either libcglue.a wasn't added to the command line, or that your libcglue.a doesn't contain "statvfs" symbol, or that the libstdcc+.a comes after libcglue.a on the linker command line. can you run make VERBOSE=1 and paste the exact psp-g++ command that is executed ?

2024-03-31 10:18 UTC, rofl0r commented on src/base/pspdev.cmake
> +SET(CMAKE_C_FLAGS_INIT "-isystem ${PSPDEV}/psp/include -I${PSPDEV}/psp/sdk/include -DPSP")
btw i learned the hard way, that CMake breaks when you change the toolchain file *after* you already configured a build. you **must** make a new build dir or expect breakage.

2024-03-31 15:01 UTC, rofl0r commented on src/base/pspdev.cmake
> +SET(CMAKE_C_FLAGS_INIT "-isystem ${PSPDEV}/psp/include -I${PSPDEV}/psp/sdk/include -DPSP")
well, i have no clue why this change affects your linking, it should only affect header lookup. are you certain it doesn't happens without this change ? also i just learned that -lcglue is added by the built-in specs, and not added explicitly to the command line

> i checked the libcglue, there's statvfs 

i'm aware this is in the source code here. but the question is whether it's in your libcglue.a. you could check with psp-nm.

either way i'm fine if we apply this only to CFLAGS, not CXXFLAGS.

2024-04-01 02:49 UTC, diamant3 requested changes

2024-04-01 02:49 UTC, diamant3 commented on src/base/pspdev.cmake
> +SET(CMAKE_C_FLAGS_INIT "-isystem ${PSPDEV}/psp/include -I${PSPDEV}/psp/sdk/include -DPSP")
Sorry for the inconvenience @rofl0r, i got the wrong branch. This is the error of the branch of your PR:

```
-- The C compiler identification is GNU 13.2.0
-- The CXX compiler identification is GNU 13.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/local/pspdev/bin/psp-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/local/pspdev/bin/psp-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/local/pspdev/bin/psp-pkg-config (found version "1.8.0") 
-- Checking for one of the modules 'sdl2'
-- Checking for one of the modules 'SDL2_image'
-- Checking for one of the modules 'SDL2_mixer'
-- Checking for one of the modules 'SDL2_ttf'
-- Checking for one of the modules 'jsoncpp'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/diamant3/Desktop/oceanpop/psp
[  4%] Building CXX object CMakeFiles/oceanpop.dir/src/Board.cpp.obj
[  8%] Building CXX object CMakeFiles/oceanpop.dir/src/BoardManager.cpp.obj
In file included from /usr/local/pspdev/psp/include/c++/13.2.0/ext/string_conversions.h:43,
                 from /usr/local/pspdev/psp/include/c++/13.2.0/bits/basic_string.h:4097,
                 from /usr/local/pspdev/psp/include/c++/13.2.0/string:54,
                 from /home/diamant3/Desktop/oceanpop/src/TextureManager.hpp:4,
                 from /home/diamant3/Desktop/oceanpop/src/BoardManager.hpp:10,
                 from /home/diamant3/Desktop/oceanpop/src/BoardManager.cpp:1:
/usr/local/pspdev/psp/include/c++/13.2.0/cstdlib:79:15: fatal error: stdlib.h: No such file or directory
   79 | #include_next <stdlib.h>
      |               ^~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/oceanpop.dir/build.make:90: CMakeFiles/oceanpop.dir/src/BoardManager.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/oceanpop.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

you just forgot the `-I` after the `-isystem`

ref: https://stackoverflow.com/questions/56318759/how-do-i-fix-the-include-next-of-stdlib-h-from-cstdlib

2024-04-01 09:48 UTC, rofl0r commented
first of all, thank you for taking the time to look at this.

> you just forgot the -I after the -isystem
>ref: https://stackoverflow.com/questions/56318759/how-do-i-fix-the-include-next-of-stdlib-h-from-cstdlib

what that once-upvoted answer suggests is to basically *not* use -isystem, answered by the OP himself through trial and error. the underlying problem here is CMake. CMake disrespects your -isystem vs -I settings and replaces one with the other, with the goal to suppress warnings.

this is a conversation i had in 2017 with a CMake contributor about this:
```irc
Jan 16 17:20:54 *	Topic for #cmake is: http://cmake.org | CMake 3.7.1 is released, yay! | Please stick around for a bit when asking questions, there may not always be somebody around | Good examples: medium: http://git.libssh.org/projects/libssh.git/ large: http://git.reactos.org/?p=reactos.git;a=tree;f=reactos
Jan 16 17:21:37 <redacted>	hi. when compiling latest inkscape, which switched to cmake, i got a build error because cmake uses -isystem instead of -I for pkg-config includes.
Jan 16 17:22:01 <redacted>	so i'd like to know why it does that
Jan 16 17:22:07 <redacted>	since it's bogus
Jan 16 17:22:38 <redacted>	c++ -isystem /include/pango-1.0 -isystem /include/harfbuzz ...
Jan 16 17:22:51 <redacted>	pkg-config --cflags --libs pango
Jan 16 17:22:51 <redacted>	-I/include/pango-1.0 -pthread -I/include/glib-2.0 -I/lib/glib-2.0/include -lpango-1.0 -lgobject-2.0 -L/lib -lglib-2.0  
Jan 16 17:28:59 <Orphis>	redacted: How are you linking against pango in CMake terms?
Jan 16 17:30:06 <redacted>	me ? i'm just someone forced to use cmake because inkscape decided that it would be better for me if i'd have to use cmake instead of configure
Jan 16 17:30:25 <Orphis>	Also, -isystem is not any different from -I, it just silences warnings
Jan 16 17:30:36 <redacted>	it *is* different
Jan 16 17:31:17 <redacted>	it builds when i dump the cmake verbose output into a shell command, and sed -i 's/isystem/I/'
Jan 16 17:32:14 <redacted>	and due to the use of isystem were -I is due, it fails to find stdlib.h included_next from cstdlib
Jan 16 17:32:59 <Orphis>	redacted: Your toolchain is badly setup then
Jan 16 17:33:29 <redacted>	Orphis, no, it's correctly set up. everything works when there are no bogus -isystem's thrown into the command line
Jan 16 17:33:50 <Orphis>	CMake isn't providing include paths for stdlib.h or cstdlib, they come from the compiler driver
Jan 16 17:34:11 <redacted>	exactly. they come from the default system include dir.
Jan 16 17:34:31 <redacted>	which you overwrite to something else by using isystem to point into harfbuzz' dir
Jan 16 17:34:50 <Orphis>	No, it's an additional search path, it's not replacing anything
Jan 16 17:34:56 <redacted>	the issue is that CMAKE OVERWRITES THE SYSTEM DIR
Jan 16 17:35:11 <Orphis>	You don't understand how the compiler is working
Jan 16 17:35:14 <redacted>	there can only be ONE -isystem path
Jan 16 17:35:19 <redacted>	i understand it very well
Jan 16 17:35:28 <redacted>	i'm building my own compilers since 2011
Jan 16 17:35:58 <Orphis>	It's a list of search path, all headers in those don't produce warnings, that's all there is
Jan 16 17:36:05 <redacted>	well, there can be thousands, but they all override the STANDARD SYSTEM INCLUDE dir
Jan 16 17:36:19 <Orphis>	If the author of inkscape pushed it, they tried and it works for them, raise the issue with them
Jan 16 17:36:29 <Orphis>	It doesn't override anything
Jan 16 17:36:33 <redacted>	how about you go to read the documentation instead of insisting you're right when you aren't ?
Jan 16 17:36:56 <Orphis>	Header files found in directories added to the search path with the -isystem
Jan 16 17:36:59 <Orphis>	ADDED
Jan 16 17:37:17 <Orphis>	https://gcc.gnu.org/onlinedocs/cpp/System-Headers.html
Jan 16 17:37:31 <redacted>	so why does it work when i do s/isystem/I/ on the command used by cmake ?
Jan 16 17:37:42 <Orphis>	It can't work
Jan 16 17:37:58 <Orphis>	Or is it "-isystem/include/foobar" ?
Jan 16 17:38:02 <Orphis>	There should be a space
Jan 16 17:38:03 <redacted>	anyway, i'm not coming here to fight with you, i'm asking how i can turn the "turn -I into -isystem"-feature of cmake off
Jan 16 17:39:16 <redacted>	i don't care if you insist that it shouldnt matter, because it does. it breaks the build.
```
CMake authors refuse to change anything on their end, or even read the GCC documentation. as soon as pkg-config is used, they add -isystem for all the include dirs provided there.

on my end, i patch cmake *not* to do that https://github.com/sabotage-linux/sabotage/blob/master/KEEP/cmake-isystem.patch

so i guess for this project the only solution is to either ship a patched cmake too, or remove the -isystem directive for C++ in my patch here (C headers dont use include_next and even cmake can't break them).

2024-04-01 10:12 UTC, diamant3 approved these changes

2024-04-01 10:13 UTC, diamant3 commented
thanks for the insight @rofl0r, looks good to me

2024-04-01 10:13 UTC, merged