Add support for Clang
pspdev/pspsdk pull request #42
Opened 2020-10-04 00:40 UTC by wally4000

Clang will not work without this patch as it fails in the autobuild section

Could you please review? 👍

2020-10-04 01:01 UTC, sajattack requested changes

2020-10-04 01:01 UTC, sajattack commented on patchinst.sh
> +# This is a hacky, makeshift script to automatically patch .S files for clang.
Perhaps this should be removed?

2020-10-04 09:00 UTC, sharkwouter commented on src/base/build.mak
> +CC       = clang
I was wondering if changing the default would cause issues with some software. It probably does

2020-10-04 09:28 UTC, sajattack commented on src/base/build.mak
> +CC       = clang
It would break everything for everyone who doesn't have clang installed. Which is pretty much everyone. This is the base for everyone's makefiles.

2021-01-12 10:57 UTC, carstene1ns commented on src/base/build.mak
> +CC       = clang
I think we should make a new conditional here to be added to user's Makefile, e.g. `USE_CLANG`.

2021-01-12 11:02 UTC, carstene1ns commented
I think we should split out the changes to conditionals (`SONYSTUBS` and friends) from here.

2021-11-23 00:41 UTC, wally4000 commented
Closing this for now.

2021-11-23 00:41 UTC, closed without merging