Update PSPSDK and make it more POSIX
pspdev/pspsdk pull request #58
Opened 2021-11-13 23:01 UTC by fjtrujy

# Description

First of all sorry for this huge PR, but it wasn't possible to do it shorter.

The original scope of this PR was to perform the needed changes to implement in `libpsplibc` the required `newlib` callbacks for creating a fully POSIX environment, however in the path, other changes have been needed.
 
Most important items:
- Add some missing headers and stubs to some user and kernel libs (LightWidth Mutex).
- Migrate code from the newlib patch to the `libpsplibc` (needed by decouple `psptoolchain` from `pspsdk`)
- Improve the logic for making thread-safe all the I/O operations and malloc/free
- Improve the logic for reserving the available `heap memory`, now by default uses everything except 512KB reserved just in case is needed for other libraries.
- Improve base makefiles, making them more simple because now `gcc` includes the standar libraries (https://github.com/pspdev/gcc/blob/133f2d65bee538e1141a9701f7f80dd4b21649ce/gcc/config/mips/psp.h#L23-L30)
- Fix an issue with `__psp_libc_init` not being called
- Add `cmake` files to base folder
- Automate generation of `doxygen`
- Compile in the CI/CD all the examples generating the proper artifacts.
- Create `pspsdk` layer 
- Include in the CI/CD compilation using the `psptoolchain` docker layer.
- Other minor issues

## POSSIBLE BREAKING CHANGES
1. Some fields from `SceIoStat` have been renamed because entered in conflicts with `newlib`
```
st_ctime -> sce_st_ctime
st_atime -> sce_st_atime
st_mtime -> sce_st_mtime
```

2. Heap allocation logic has been changed. 
Previously we just have a macro called `PSP_HEAP_SIZE_MAX` for using the whole `heap memory`, now we have a  macro called `PSP_HEAP_THRESHOLD_SIZE_KB`, where you can define the `threshold you leave available`. The default value is **`512KB`**
So, `PSP_HEAP_THRESHOLD_SIZE_KB(0)` is exactly the same that before was `PSP_HEAP_SIZE_MAX()`

3. Removed macro `PSPSDK_LIBC_LIB`, now we always link with `newlib + libpsplibc` & using standard libraries, however, the option `USE_KERNEL_LIBS` is still available.

4. Some other unexpected issues.

### MORE INFO
This PR is part of a collection of PRs, where the whole `pspdev` environment for development is being improved, with the main objectives of getting a more POSIX & Standard toolchain and integrating a CI/CD workflow to increase testability and reliability.

Others PRs related:
https://github.com/pspdev/psp-pacman/pull/15
https://github.com/pspdev/psptoolchain-extra/pull/1
https://github.com/pspdev/psptoolchain-allegrex/pull/1
https://github.com/pspdev/psptoolchain/pull/160

Here you have more info about the new repo structures, artifacts, and docker layers generated:

![layers](https://user-images.githubusercontent.com/10010409/141652593-0a666f65-c4a2-47a2-a2ac-10bde76e492f.png)

Thanks

2021-11-14 01:16 UTC, sajattack requested changes
Leaving my comment from discord here as well so it's not forgotten:

What you're calling psplibc here isn't a full libc and is very different to the previous psplibc (I think). I would like it renamed. Something like libcglue or libposixinterface or whatever we can come up with.

2021-11-15 13:40 UTC, carstene1ns reviewed
some nits.

2021-11-15 13:40 UTC, carstene1ns commented on src/libcglue/errno.c
> + * init.c - The global init/deinit code for our crt0.
errno.c

2021-11-15 13:40 UTC, carstene1ns commented on configure.ac
> +PSPSDK_CFLAGS="$CFLAGS -G0 -O3 -Wall"
please remove, so the user can have their own (e.g. `-O0` for debugging), autotools will automatically set `-O2` when nothing is set.

2021-11-15 13:40 UTC, carstene1ns commented on src/libcglue/cwd.c
> + * init.c - The global init/deinit code for our crt0.
cwd.c

2021-11-15 13:40 UTC, carstene1ns commented on src/libcglue/timezone.c
> + * timezon.c - Set proper timezone needed by newlib.
timezone.c

2021-11-15 13:40 UTC, carstene1ns commented on src/samples/Makefile.am
> +	rm -rf `find $(distdir) -name .svn -o -name CVS`
There should be no traces of subversion or cvs around anymore. Why do you revert (https://github.com/pspdev/pspsdk/commit/d88103a9be5bde6599a279cbdfe1b080fb87dc09#diff-3368d769c27792b586069451459f50fb33504e5b99bcfd17e841dd7a9e3128cd) to an older version and stripping my comment?

2021-11-15 13:40 UTC, carstene1ns commented on Makefile.am
> +EXTRA_DIST = LICENSE VERSION README.md Doxyfile doc/html
This likely breaks `make distcheck`

2021-11-15 13:40 UTC, carstene1ns commented on src/startup/Makefile.am
> +lib_a_SOURCES = crt0.c crt0_prx.c prxexports.c
Does this work?

2021-11-15 13:45 UTC, fjtrujy commented on src/startup/Makefile.am
> +lib_a_SOURCES = crt0.c crt0_prx.c prxexports.c
Yes, I tried with several applications, ELF and PRXs both working

2021-11-15 13:45 UTC, fjtrujy commented on src/libcglue/errno.c
> + * init.c - The global init/deinit code for our crt0.
Thanks

2021-11-15 13:46 UTC, carstene1ns commented
Can you please explain why the weak reference to `__psp_libc_init` does not work like before and we need to resort to another macro when wanting to disable it?

2021-11-15 13:50 UTC, carstene1ns commented on src/startup/Makefile.am
> +lib_a_SOURCES = crt0.c crt0_prx.c prxexports.c
So no need to feed the crt0.o into a first stage installation anymore?

2021-11-15 13:58 UTC, fjtrujy commented on src/startup/Makefile.am
> +lib_a_SOURCES = crt0.c crt0_prx.c prxexports.c
Nop. I recommend you to take a look to the graph attached here:

The toolchain is composed by:
1. Binutils 
2. Gdb
3. Gcc phase 1
4. Newlib
5. Gcc phase 2

This was one of the most important things why I wanted to do that, fully separate pspsdk from psptoolchain

2021-11-15 14:07 UTC, fjtrujy commented
> Can you please explain why the weak reference to `__psp_libc_init` does not work like before and we need to resort to another macro when wanting to disable it?

So there is more than one topic here:
First this one, it wasn't working properly
https://github.com/pspdev/pspsdk/issues/56

Then secondly, now by default, we always link using `newlib` unless we decide to use `USE_KERNEL_LIBS`
So by default the `__psp_libc_init` must be called, if for whatever reason, you don't want to call this init, you still can override the function because `__psp_libc_init` is defined as weak in `src/libcglue/init.c`.

The reason why I created that macro is like a "shortcut" for users that fully want to disable the `psp_libc_init` (only good reason is if you aren't going to use anything about `newlib` and you want to have a super tiny binary)

2021-11-15 14:17 UTC, fjtrujy commented
> Leaving my comment from discord here as well so it's not forgotten:
> 
> What you're calling psplibc here isn't a full libc and is very different to the previous psplibc (I think). I would like it renamed. Something like libcglue or libposixinterface or whatever we can come up with.

We have finally renamed to `libcglue`, thanks for the suggestion

2021-11-15 14:30 UTC, fjtrujy commented on src/samples/Makefile.am
> +	rm -rf `find $(distdir) -name .svn -o -name CVS`
I think it was probably a mistake that I did. Removing thing that.
The comment is not anymore needed, because I have fixed that you said there 😄

2021-11-15 14:38 UTC, fjtrujy commented on Makefile.am
> +EXTRA_DIST = LICENSE VERSION README.md Doxyfile doc/html
Thanks, fixing it!

2021-11-15 14:43 UTC, fjtrujy commented
Hello @carstene1ns,
I have renamed `__psp_libc_init` to `__libcglue_init`, maybe now is clearer to understand what does it means.

Thanks

2021-11-16 01:10 UTC, sajattack commented on src/libcglue/glue.c
> +	// TODO: Implement proper functionality
TODOs?

2021-11-16 16:51 UTC, sajattack approved these changes

2021-11-17 01:47 UTC, merged